#!/usr/bin/env node

const path = require("path");
const spawn = require("child_process").spawn;

const inputArgs = process.argv.slice(2);

let bin = "";
let args = [];

if (inputArgs[0] == "link") {
  bin = path.join(__dirname, "rnw-link");
  args = inputArgs.slice(1)
  console.log('\x1b[36m%s\x1b[0m', `Starting rnw link`);
} else if(inputArgs[0] == "watch") {
  console.log('\x1b[36m%s\x1b[0m', `Starting rnw watch`);
  bin = "wml"
  args = ["start"]
} else {
  console.log('\x1b[31m%s\x1b[0m', 'Command does not exist')
  process.exit()
}

const ls = spawn(bin, args);

ls.stdout.on("data", data => {
  console.log(`${data}`);
});

ls.stderr.on("data", data => {
  console.error(`${data}`);
});

ls.on("close", code => {
  console.log(`child process exited with code ${code}`);
});
